### ISSUE TITLE
running 'cargo doc' on rust stable produces error

### ISSUE THREAD

**Issue by stepkun** [SoftbearStudios/bitcode#18]
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcode-0.5.1/src/lib.rs:2:18
  |
2 | #![cfg_attr(doc, feature(doc_cfg))]
  |                  ^^^^^^^^^^^^^^^^

**Comment by caibear** [comment]
This is expected since we used `#![feature(dog_cfg)]` to show that functions like `bitcode::serialize` require serde https://docs.rs/bitcode/0.5.0/bitcode/fn.serialize.html

If you want to run the docs or tests yourself you'll have to use nightly. To do so, you can run this inside the bitcode project:
```
rustup override set nightly
```

**Comment by aecsocket** [comment]
This breaks `cargo doc` for all users of this dependency who use stable Rust, which is counterproductive. Users shouldn't be punished for using stable, and running `cargo doc` locally is a perfectly valid use case. Consider changing this to something like
```rs
#![cfg_attr(any(nightly, docsrs), feature(doc_cfg, doc_auto_cfg))]
```
I use this in my own stable crate, and it lets me run `cargo doc` just fine while still enabling `doc_cfg` on docs.rs.

**Comment by caibear** [comment]
This has been fixed on the [latest alpha version](https://github.com/SoftbearStudios/bitcode/pull/19) `bitcode = "=0.6.0-alpha.2"`.
